services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        API_BASE_URL: apinimeninja.work.gd
        CDN_WORKER_URL: video-auth-worker.nime-ninja.workers.dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
