services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        API_BASE_URL: https://api.nimeninja.win
        NEXT_PUBLIC_SITE_URL: https://app.nimeninja.win
        REDIS_REST_URL: https://emerging-cougar-56286.upstash.io
        REDIS_REST_TOKEN: AdveAAIjcDEzNzgzNDFmMDJlOGE0NTY1OWZiOTgwYTFmOWI1NzM3ZXAxMA
        CDN_WORKER_URL: https://video-auth-worker.nime-ninja.workers.dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
