services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        API_BASE_URL: https://apinimeninja.work.gd
        NEXT_PUBLIC_SITE_URL: http://dev.local:4000
        REDIS_REST_URL: https://emerging-cougar-56286.upstash.io
        REDIS_REST_TOKEN: AdveAAIjcDEzNzgzNDFmMDJlOGE0NTY1OWZiOTgwYTFmOWI1NzM3ZXAxMA
        CDN_WORKER_URL: https://video-auth-worker.nime-ninja.workers.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    restart: unless-stopped
